import { Produto } from "./produtos";

export const PRODUTOS: Produto[] = [
    {
        Id: 1, Nome: "Teste1", img: "https://images-submarino.b2w.io/produtos/01/00/item/132134/3/132134369P1.jpg", preco: 199.99, descricao: "A Câmera Ideal para Selfies, Paisagens ou Retratos de Família As câmeras do iPhone 6 Plus possuem exatamente a mesma configuração do iPhone 6: 8 megapixels para a principal e 1, 2 megapixel para a frontal.Apesar desses números serem os mesmos desde o iPhone 5, é importante destacar que as mudanças continuam sendo realizadas internamente.A abertura da lente principal de F / 2.2 proporciona maior incidência de luz e, consequentemente, melhor qualidade dos cliques.O 6 Plus filma em Full HD com resolução de até 720p."},
    { Id: 2, Nome: "Teste2", img: "https://images-submarino.b2w.io/produtos/01/03/item/132386/1/132386144P1.jpg", preco: 399.99, descricao: "A Câmera Ideal para Selfies, Paisagens ou Retratos de Família As câmeras do iPhone 6 Plus possuem exatamente a mesma configuração do iPhone 6: 8 megapixels para a principal e 1, 2 megapixel para a frontal.Apesar desses números serem os mesmos desde o iPhone 5, é importante destacar que as mudanças continuam sendo realizadas internamente.A abertura da lente principal de F / 2.2 proporciona maior incidência de luz e, consequentemente, melhor qualidade dos cliques.O 6 Plus filma em Full HD com resolução de até 720p." },
    { Id: 3, Nome: "Teste3", img: "https://images-submarino.b2w.io/produtos/01/00/item/133453/1/133453185P1.jpg", preco: 99.39, descricao: "A Câmera Ideal para Selfies, Paisagens ou Retratos de Família As câmeras do iPhone 6 Plus possuem exatamente a mesma configuração do iPhone 6: 8 megapixels para a principal e 1, 2 megapixel para a frontal.Apesar desses números serem os mesmos desde o iPhone 5, é importante destacar que as mudanças continuam sendo realizadas internamente.A abertura da lente principal de F / 2.2 proporciona maior incidência de luz e, consequentemente, melhor qualidade dos cliques.O 6 Plus filma em Full HD com resolução de até 720p." },
    { Id: 4, Nome: "Teste4", img: "https://images-submarino.b2w.io/produtos/01/00/item/132134/3/132134369P1.jpg", preco: 199.99, descricao: "A Câmera Ideal para Selfies, Paisagens ou Retratos de Família As câmeras do iPhone 6 Plus possuem exatamente a mesma configuração do iPhone 6: 8 megapixels para a principal e 1, 2 megapixel para a frontal.Apesar desses números serem os mesmos desde o iPhone 5, é importante destacar que as mudanças continuam sendo realizadas internamente.A abertura da lente principal de F / 2.2 proporciona maior incidência de luz e, consequentemente, melhor qualidade dos cliques.O 6 Plus filma em Full HD com resolução de até 720p." },
    { Id: 5, Nome: "Teste5", img: "https://images-submarino.b2w.io/produtos/01/03/item/132386/1/132386144P1.jpg", preco: 399.99, descricao: "A Câmera Ideal para Selfies, Paisagens ou Retratos de Família As câmeras do iPhone 6 Plus possuem exatamente a mesma configuração do iPhone 6: 8 megapixels para a principal e 1, 2 megapixel para a frontal.Apesar desses números serem os mesmos desde o iPhone 5, é importante destacar que as mudanças continuam sendo realizadas internamente.A abertura da lente principal de F / 2.2 proporciona maior incidência de luz e, consequentemente, melhor qualidade dos cliques.O 6 Plus filma em Full HD com resolução de até 720p." },
    { Id: 6, Nome: "Teste6", img: "https://images-submarino.b2w.io/produtos/01/00/item/133453/1/133453185P1.jpg", preco: 99.39, descricao: "A Câmera Ideal para Selfies, Paisagens ou Retratos de Família As câmeras do iPhone 6 Plus possuem exatamente a mesma configuração do iPhone 6: 8 megapixels para a principal e 1, 2 megapixel para a frontal.Apesar desses números serem os mesmos desde o iPhone 5, é importante destacar que as mudanças continuam sendo realizadas internamente.A abertura da lente principal de F / 2.2 proporciona maior incidência de luz e, consequentemente, melhor qualidade dos cliques.O 6 Plus filma em Full HD com resolução de até 720p." },
    { Id: 7, Nome: "Teste7", img: "https://images-submarino.b2w.io/produtos/01/00/item/132134/3/132134369P1.jpg", preco: 199.99, descricao: "A Câmera Ideal para Selfies, Paisagens ou Retratos de Família As câmeras do iPhone 6 Plus possuem exatamente a mesma configuração do iPhone 6: 8 megapixels para a principal e 1, 2 megapixel para a frontal.Apesar desses números serem os mesmos desde o iPhone 5, é importante destacar que as mudanças continuam sendo realizadas internamente.A abertura da lente principal de F / 2.2 proporciona maior incidência de luz e, consequentemente, melhor qualidade dos cliques.O 6 Plus filma em Full HD com resolução de até 720p."},
    { Id: 8, Nome: "Teste8", img: "https://images-submarino.b2w.io/produtos/01/03/item/132386/1/132386144P1.jpg", preco: 399.99, descricao: "A Câmera Ideal para Selfies, Paisagens ou Retratos de Família As câmeras do iPhone 6 Plus possuem exatamente a mesma configuração do iPhone 6: 8 megapixels para a principal e 1, 2 megapixel para a frontal.Apesar desses números serem os mesmos desde o iPhone 5, é importante destacar que as mudanças continuam sendo realizadas internamente.A abertura da lente principal de F / 2.2 proporciona maior incidência de luz e, consequentemente, melhor qualidade dos cliques.O 6 Plus filma em Full HD com resolução de até 720p." },
    { Id: 9, Nome: "Teste9", img: "https://images-submarino.b2w.io/produtos/01/00/item/133453/1/133453185P1.jpg", preco: 99.39, descricao: "A Câmera Ideal para Selfies, Paisagens ou Retratos de Família As câmeras do iPhone 6 Plus possuem exatamente a mesma configuração do iPhone 6: 8 megapixels para a principal e 1, 2 megapixel para a frontal.Apesar desses números serem os mesmos desde o iPhone 5, é importante destacar que as mudanças continuam sendo realizadas internamente.A abertura da lente principal de F / 2.2 proporciona maior incidência de luz e, consequentemente, melhor qualidade dos cliques.O 6 Plus filma em Full HD com resolução de até 720p." },
];